name: protobuf_serializable_components_generator
description: Standalone code generator for protobuf_serializable_components.
version: 1.0.0

environment:
  sdk: ^3.12.1

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.4
  glob: ^2.1.3
  source_gen: ^4.2.0
  protobuf_serializable_components:
    git:
      url: https://github.com/vunyunt/protobuf_serializable_components.git
      ref: main


dev_dependencies:
  lints: ^6.0.0
