import 'dart:async';

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:source_gen/source_gen.dart';

class CoreSerializableComponentsBuilder extends Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': [
      'components/serializable/register_serializable_components.g.dart',
    ],
  };

  bool _implementsSerializableComponent(ClassElement element) {
    for (final interface in element.allSupertypes) {
      if (interface.element.name == 'ProtoSerializable') {
        return true;
      }
    }
    return false;
  }

  String? _getProtoTypeName(ClassElement element) {
    for (final interface in element.allSupertypes) {
      if (interface.element.name == 'ProtoSerializable') {
        final typeArg = interface.typeArguments.isNotEmpty
            ? interface.typeArguments.first
            : null;
        return typeArg?.element?.name;
      }
    }
    return null;
  }

  bool _hasValidConstructor(ClassElement element) {
    return element.constructors.any(_isValidConstructor);
  }

  bool _isValidConstructor(ConstructorElement constructor) {
    final positionalParams = constructor.formalParameters
        .where((p) => p.isPositional)
        .toList();
    if (positionalParams.length != 1) return false;

    final otherRequiredParams = constructor.formalParameters.where((p) {
      if (p == positionalParams.first) return false;
      return p.isRequired;
    });

    if (otherRequiredParams.isNotEmpty) return false;

    return true;
  }

  bool _constructorHasRegistryParam(ClassElement element) {
    ConstructorElement? validConstructor;
    for (final constructor in element.constructors) {
      if (_isValidConstructor(constructor)) {
        validConstructor = constructor;
        break;
      }
    }
    validConstructor ??= element.unnamedConstructor;
    if (validConstructor == null) return false;

    return validConstructor.formalParameters.any(
      (p) =>
          p.isNamed &&
          p.name == 'registry' &&
          p.type.element?.name == 'SerializableComponentRegistry',
    );
  }

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final allFiles = await buildStep
        .findAssets(Glob('lib/**/*.sc.dart'))
        .toList();

    allFiles.sort();

    final factories =
        <
          String,
          ({String className, String importLine, bool hasRegistryParam})
        >{};

    final packageName = buildStep.inputId.package;

    for (final file in allFiles) {
      final library = await buildStep.resolver.libraryFor(file);
      final libraryReader = LibraryReader(library);

      for (final clazz in libraryReader.allElements.whereType<ClassElement>()) {
        final className = clazz.name;
        if (className == null) continue;

        final importPath = file.path.replaceFirst('lib/', 'package:$packageName/');
        final importLine = 'import "$importPath";';

        if (_implementsSerializableComponent(clazz) && !clazz.isAbstract) {
          final protoTypeName = _getProtoTypeName(clazz);
          final hasValidConstructor = _hasValidConstructor(clazz);

          if (protoTypeName != null && hasValidConstructor) {
            final hasRegistryParam = _constructorHasRegistryParam(clazz);
            factories[protoTypeName] = (
              className: className,
              importLine: importLine,
              hasRegistryParam: hasRegistryParam,
            );
          }
        }
      }
    }

    final allProtoTypes = factories.keys.toList()..sort();
    final allImportLines = factories.values.map((v) => v.importLine).toList()
      ..sort();

    final registerLines = <String>[];
    for (final protoType in allProtoTypes) {
      final factory = factories[protoType]!;

      final registryArg = factory.hasRegistryParam
          ? ', registry: registry'
          : '';

      registerLines.add('''
  registry.registerDescriptor(
    ComponentDescriptor(
      defaultInstance: $protoType.getDefault(),
      factory: (data, {registry}) => ${factory.className}(data as $protoType$registryArg),
    ),
  );''');
    }

    final importLines = allImportLines.join('\n');
    final registerContent = registerLines.join('\n');

    final outputContent =
        '''
// This file is automatically generated. Do not edit manually.
// Generated by CoreSerializableComponentsBuilder

import 'package:protobuf_serializable_components/protobuf_serializable_components.dart';
import 'package:frogsoup_model/frogsoup_model.dart';

$importLines

void registerSerializableComponents(SerializableComponentRegistry registry) {
$registerContent
}''';

    await buildStep.writeAsString(
      AssetId(
        buildStep.inputId.package,
        'lib/components/serializable/register_serializable_components.g.dart',
      ),
      outputContent,
    );
  }
}
