import 'dart:async';
import 'package:build/build.dart';
import 'package:glob/glob.dart';

class DescriptorRegistryBuilder extends Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': ['src/descriptor_registry.g.dart'],
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    // Find all .pbjson.dart files in the models directory
    final pbjsonFiles = await buildStep
        .findAssets(Glob('lib/models/proto_gen/**/*.pbjson.dart'))
        .toList();

    // Sort files to ensure consistent output
    pbjsonFiles.sort();

    final descriptorMapEntries = <String>[];
    for (final asset in pbjsonFiles) {
      final library = await buildStep.resolver.libraryFor(asset);

      // Infer package from path: lib/models/proto_gen/path/to/file.pbjson.dart
      // Package: path.to (removing the filename part)
      final pathParts = asset.path.split('/');
      final protoGenIndex = pathParts.indexOf('proto_gen');
      String package = '';
      if (protoGenIndex != -1 && pathParts.length > protoGenIndex + 1) {
        // Exclude 'lib/models/proto_gen/' and the filename
        final packageParts = pathParts.sublist(
          protoGenIndex + 1,
          pathParts.length - 1,
        );
        package = packageParts.join('.');
      }

      for (final element in library.topLevelVariables) {
        final typeName = element.type.getDisplayString();
        final name = element.name;
        if (name == null) continue;

        // Look for variables named *Descriptor that are Uint8List
        if (name.endsWith('Descriptor') &&
            (typeName == 'Uint8List' || typeName.endsWith('.Uint8List'))) {
          // Try to find the corresponding message name from the variable name
          // characterProtoDescriptor -> CharacterProto
          // We assume the message name starts with uppercase.
          final baseName = name.replaceAll('Descriptor', '');
          // baseName might be 'characterProto'
          // We need 'CharacterProto'
          // We can find the variable ending in $json to get the exact casing.
          String messageName = baseName;
          for (final v in library.topLevelVariables) {
            final vName = v.name;
            if (vName == null) continue;
            if (vName.toLowerCase() == '${baseName.toLowerCase()}\$json') {
              messageName = vName.replaceAll('\$json', '');
              break;
            }
          }

          final qualifiedName = package.isEmpty
              ? messageName
              : '$package.$messageName';
          descriptorMapEntries.add("  '$qualifiedName': $name,");
        }
      }
    }

    final output =
        '''
// This file is automatically generated. Do not edit manually.
// Generated by DescriptorRegistryBuilder

import 'dart:typed_data';
import 'package:${buildStep.inputId.package}/protobuf_pbjson_exports.g.dart';

final descriptorRegistryMap = <String, Uint8List>{
${descriptorMapEntries.join('\n')}
};
''';

    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package, 'lib/src/descriptor_registry.g.dart'),
      output,
    );
  }
}

Builder descriptorRegistryBuilder(BuilderOptions options) =>
    DescriptorRegistryBuilder();
