import 'dart:async';
import 'package:build/build.dart';
import 'package:glob/glob.dart';

class ExportIndexBuilder extends Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': [
      'protobuf_exports.g.dart',
      'protobuf_pbjson_exports.g.dart',
    ],
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    await _generateExportFile(
      buildStep,
      glob: 'lib/models/proto_gen/**/*.pb.dart',
      outputFileName: 'protobuf_exports.g.dart',
    );

    await _generateExportFile(
      buildStep,
      glob: 'lib/models/proto_gen/**/*.pbjson.dart',
      outputFileName: 'protobuf_pbjson_exports.g.dart',
    );
  }

  Future<void> _generateExportFile(
    BuildStep buildStep, {
    required String glob,
    required String outputFileName,
  }) async {
    final files = await buildStep.findAssets(Glob(glob)).toList();
    files.sort();

    log.info('Found ${files.length} files for $outputFileName');

    final exportLines = <String>[
      '// This file is automatically generated. Do not edit manually.',
      '// Generated by ExportIndexBuilder',
      '',
    ];

    for (final asset in files) {
      final relativePath = asset.path.replaceFirst('lib/', '');
      exportLines.add("export '$relativePath';");
    }

    final outputContent = exportLines.join('\n');
    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package, 'lib/$outputFileName'),
      outputContent,
    );
  }
}

Builder exportIndexBuilder(BuilderOptions options) => ExportIndexBuilder();
